"""add workspace member uniqueness

Revision ID: 4aca36ab8c7f
Revises: f21f8936d2da
Create Date: 2026-07-30 22:19:11.411356

"""

from collections.abc import Sequence

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "4aca36ab8c7f"
down_revision: str | None = "f21f8936d2da"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "uq_workspace_members_workspace_user",
        "workspace_members",
        ["workspace_id", "user_id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "uq_workspace_members_workspace_user",
        "workspace_members",
        type_="unique",
    )
    # ### end Alembic commands ###
